server:
  port: 8888
  servlet:
    context-path: /

spring:
  profiles:
    active: develop
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #dataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sz_1902?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
#映射文件路径
mybatis:
  mapper-locations: classpath:/mapper/*.xml

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true